version: 2
jobs:
  build:
    working_directory: ~/dynamodb-viewer
    docker:
      - image: node:6.10.2-slim
    steps:
      - checkout
      - restore_cache:
          key: depsl-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: depsl-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn run build
