version: 2
jobs:
  build:
    working_directory: ~/dynamodb-viewer
    docker:
      - image: node:6.10.2-slim
    steps:
      - checkout
      - restore_cache:
          key: depsl-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: depsl-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn run build
      - deploy:
          name: Deploy master to S3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mv dist/index.html index.html
              aws s3 sync dist s3://dynamodb-viewer --delete --cache-control 'public, max-age=31536000'
              aws s3 cp index.html s3://dynamodb-viewer/index.html --cache-control 'no-cache, no-store, must-revalidate'
            fi
